apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: "{{ .Release.Name }}-elasticsearch"
  replicas: {{ .Values.elasticsearch.replicaCount }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: {{ .Values.elasticsearch.service.restPort }}  
            - containerPort: {{ .Values.elasticsearch.service.clusterPort }} 
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-elasticsearch-config
  volumeClaimTemplates:  
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - {{ .Values.elasticsearch.storage.accessMode }}
        resources:
          requests:
            storage: {{ .Values.elasticsearch.storage.size }}
        storageClassName: {{ .Values.elasticsearch.storage.storageClass }}
        volumeName: "elasticsearch-pvtenjin"  
