apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
    app: elasticsearch
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.elasticsearch.service.restPort }}
      targetPort: {{ .Values.elasticsearch.service.restPort }}
      
    - name: transport
      protocol: TCP
      port: {{ .Values.elasticsearch.service.clusterPort }}
      targetPort: {{ .Values.elasticsearch.service.clusterPort }}
