apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
spec:
  type: {{ .Values.kibana.service.type }}
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: {{ .Values.kibana.service.port }}
      targetPort: {{ .Values.kibana.service.port }}
