apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin
spec:
  type: {{ .Values.tenjin.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.tenjin.service.port }}
      targetPort: {{ .Values.tenjin.service.port }}
